name: CI
on:
  push:
  pull_request:
jobs:
  test:
    container: 
      image: swift:5.8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: swift test --enable-code-coverage --sanitize=thread
    - name: Setup container for codecov upload
      run: apt-get update && apt-get install curl -y
    - name: Process coverage file
      run: llvm-cov show .build/x86_64-unknown-linux-gnu/debug/VaporSecurityHeadersPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata > coverage.txt
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_UPLOAD_KEY }}
        file: coverage.txt
